# Generated by Django 4.0.4 on 2022-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Ca', 'Cash'), ('Cr', 'Credit Card'), ('De', 'Debit Card'), ('Pp', 'Paypal')], default='Ca', max_length=2),
        ),
    ]
