# Generated by Django 4.0.4 on 2022-06-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='credit_card_cvv',
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_card_expiration_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='credit_card_number',
        ),
    ]
