# Generated by Django 4.0.4 on 2022-07-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Ca', 'Cash'), ('Cr', 'Credit Card'), ('De', 'Debit Card'), ('Pp', 'Paypal')], default='Ca', max_length=2),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
