# Generated by Django 4.0.4 on 2022-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_cart_id_alter_cart_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
