default:
    ALLOWED_HOSTS:
        - '*'
    INSTALLED_APPS:
        - django.contrib.admin
        - django.contrib.auth
        - django.contrib.contenttypes
        - django.contrib.sessions
        - django.contrib.messages
        - django.contrib.staticfiles
        - 'rest_framework'
        - 'inventory'
        - 'store'
production:
    DEBUG: TRUE
    ALLOWED_HOSTS:
        - 'server.prod.com'
