# Generated by Django 4.0.4 on 2022-05-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='Here some Text', max_length=1000),
        ),
    ]
